-- Add up migration script here

DROP TABLE IF EXISTS USER_ROADMAP_AREAS;
DROP TABLE IF EXISTS USER_ROADMAPS;
DROP TABLE IF EXISTS ROADMAP_AREAS;
DROP TABLE IF EXISTS ROADMAPS;

-- TODO: add versioning later? or better approach would be allowing user to duplicate it.

CREATE TABLE ROADMAPS (
    ID VARCHAR(32) PRIMARY KEY,
    TITLE VARCHAR(32) NOT NULL,
    DESCRIPTION TEXT,
    PUBLISHER VARCHAR(32) NOT NULL, 
    PUBLISHED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW(),

    CONSTRAINT PUBLISHER_FK FOREIGN KEY (PUBLISHER) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);

CREATE TABLE ROADMAP_AREAS (
    ID VARCHAR(32) PRIMARY KEY,
    PARENT_ID VARCHAR(32) REFERENCES ROADMAP_AREAS(ID) ON DELETE CASCADE,
    ROADMAP_ID VARCHAR(32) NOT NULL REFERENCES ROADMAPS(ID) ON DELETE CASCADE,
    TITLE VARCHAR(32) NOT NULL,
    DESCRIPTION TEXT,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW()
);


CREATE TABLE USER_ROADMAPS (
    ID VARCHAR(32) PRIMARY KEY,
    USER_ID VARCHAR(32) NOT NULL,
    ROADMAP_ID VARCHAR(32) NOT NULL,

    CREATED_AT TIMESTAMP DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW(),

    CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USERNAME) ON DELETE CASCADE,
    CONSTRAINT ROADMAP_ID_FK FOREIGN KEY (ROADMAP_ID) REFERENCES ROADMAPS(ID) ON DELETE CASCADE 
);


CREATE TABLE USER_ROADMAP_AREAS (
    USER_ROADMAP_ID VARCHAR(32) NOT NULL,
    AREA_ID VARCHAR(32) NOT NULL,
    COMPLETED BOOL DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW(),

    PRIMARY KEY(USER_ROADMAP_ID, AREA_ID),
    CONSTRAINT USER_ROADMAP_ID_FK FOREIGN KEY (USER_ROADMAP_ID) REFERENCES USER_ROADMAPS(ID),
    CONSTRAINT AREA_ID_FK FOREIGN KEY (AREA_ID) REFERENCES ROADMAP_AREAS(ID)
);

