version: '3.8'  

services:
  postgres:
    image: postgres:latest  
    container_name: postgres_db  
    environment:
      POSTGRES_USER: myuser      
      POSTGRES_PASSWORD: mypassword  
      POSTGRES_DB: mydatabase    
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  
      - ./init-scripts:/docker-entrypoint-initdb.d:ro  

volumes:
  postgres_data:
    driver: local  
