version: '3.8'  

services:
  postgres:
    image: postgres:latest  
    container_name: postgres_db  
    environment:
      POSTGRES_USER: myuser      
      POSTGRES_PASSWORD: mypassword  
      POSTGRES_DB: mydatabase    
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  
      - ./init-scripts:/docker-entrypoint-initdb.d:ro  

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3030:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitoring
    depends_on:
      - prometheus


volumes:
  postgres_data:
    driver: local  
  prometheus_data:
  grafana_data:

networks:
  monitoring:
